name: "deploy"
author : "Victor DURAND"
description: "Deploie le backend FNAEG sur les serveurs de SUPALTA"
on : 
  push:
    branches:
      - master

jobs:
  build:
    steps:
      - name : Init 
      - uses: actions/checkout@v1
      
      - name: Copy Environnement
        run : php -R "file_exists('.env') || copy('.env.ci', '.env');"


      - name: Install composer dependencies
        run: composer install --no-scripts

      - name: Generate key
        run: php artisan key:generate